---
name: Ministral 3B (Local)
version: 1.0.0
schema: v1

models:
  - name: Ministral 3B (Instruct)
    provider: ollama
    model: hf.co/unsloth/Ministral-3-3B-Instruct-2512-GGUF:Q4_1
    roles:
      - chat
      - edit
    defaultCompletionOptions:
      temperature: 0.15

  - name: Ministral 3B (Reasoning)
    provider: ollama
    model: hf.co/unsloth/Ministral-3-3B-Reasoning-2512-GGUF:Q4_1
    roles:
      - chat
      - edit
    defaultCompletionOptions:
      temperature: 0.7
      top_p: 0.95
      reasoning: true