---
name: Mistral (Local)
version: 1.0.0
schema: v1

models:
  - name: Ministral 3B (Instruct)
    provider: ollama
    model: hf.co/unsloth/Ministral-3-3B-Instruct-2512-GGUF:Q6_K
    roles:
      - chat

  - name: Ministral 3B (Reasoning)
    provider: ollama
    model: hf.co/unsloth/Ministral-3-3B-Reasoning-2512-GGUF:Q6_K
    roles:
      - chat
