---
name: Qwen 3 Embedding @ Homelab
version: 1.0.0
schema: v1

models:
  - name: Qwen 3 Embedding 0.6B @ Homelab
    provider: ollama
    model: hf.co/Qwen/Qwen3-Embedding-0.6B-GGUF:Q8_0
    apiBase: http://192.168.0.2:11434
    roles:
      - embed
